version: "3"

services:
  nginx:
    container_name: "nginx"

    build:
      dockerfile: "./docker/nginx/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - "./server:/var/www/html"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./server:/var/www/html

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db:/var/lib/mysql

volumes:
  db-data:
